---
title: "Instacart Plot Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: paper
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(plotly)
library(tidyverse)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Number of Repeat Orders by Department

```{r}

instacart %>% 
  filter(reordered == 1) %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Distributions of Order Times of Selected Departments

```{r}

instacart %>% 
  filter(department == c("produce", "snacks", "beverages", 
                         "frozen", "dairy eggs", "meat seafood", 
                         "deli", "pantry", "alcohol")) %>% 
  plot_ly(x = ~department, y = ~order_hour_of_day, color = ~department, type = "box")

```

### Distribution of Number of Products Ordered per Customer 

```{r}

instacart %>% 
  group_by(user_id) %>% 
  summarize(product_count = n()) %>% 
  arrange(-product_count) %>% 
  plot_ly(
    x = ~product_count, type = "histogram", marker = list(line = list(color = 'white', width = 1))) %>% 
  layout(yaxis = list(title = list(text = 'customer_count')))

# Cannot knit: rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")

```


